package com.aurum.bistterminal8
import android.app.*
import android.content.Intent
import android.net.Uri
import android.os.*
import android.webkit.*
import androidx.webkit.WebViewAssetLoader
import org.json.JSONObject
import java.util.ArrayDeque
class PipelineService:Service(){
 data class Work(val epoch:Long,val token:String,val kind:String,val startId:Int)
 private val queue=ArrayDeque<Work>();private var active:Work?=null;private var webView:WebView?=null;private var wakeLock:PowerManager.WakeLock?=null;private val handler by lazy{Handler(mainLooper)};private var watchdog:Runnable?=null
 private inner class Bridge{@JavascriptInterface fun call(message:String,body:String)=handleNative(message,body)}
 override fun onCreate(){super.onCreate();val ch="aurum_background_pipeline";getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel(ch,"Aurum otomatik çalışmalar",NotificationManager.IMPORTANCE_LOW));startForeground(2020,Notification.Builder(this,ch).setContentTitle("Aurum").setContentText("Planlanan veri çalışması yürütülüyor").setSmallIcon(android.R.drawable.stat_notify_sync).setOngoing(true).build())}
 override fun onStartCommand(intent:Intent?,flags:Int,startId:Int):Int{val epoch=intent?.getLongExtra("epoch",0L)?.takeIf{it>0}?:run{stopSelf(startId);return START_NOT_STICKY};val token=intent.getStringExtra("jobToken")?:run{stopSelf(startId);return START_NOT_STICKY};val kind=intent.getStringExtra("pipelineKind").let{if(it=="market")"market" else "data"};if(active?.token!=token&&queue.none{it.token==token}&&SchedulerLedger.status(this,token)!="COMPLETED")queue.addLast(Work(epoch,token,kind,startId));startNext();return START_NOT_STICKY}
 private fun startNext(){if(active!=null)return;val work=queue.pollFirst()?:run{stopSelf();return};active=work;SchedulerLedger.running(this,work.token);watchdog=Runnable{finishActive(false,"PIPELINE_TIMEOUT")}.also{handler.postDelayed(it,2*60*60*1000L)};val loader=WebViewAssetLoader.Builder().addPathHandler("/assets/",WebViewAssetLoader.AssetsPathHandler(this)).build();webView=WebView(this).apply{settings.javaScriptEnabled=true;settings.domStorageEnabled=true;settings.databaseEnabled=true;settings.allowFileAccess=false;settings.allowContentAccess=false;settings.mixedContentMode=android.webkit.WebSettings.MIXED_CONTENT_NEVER_ALLOW;addJavascriptInterface(Bridge(),"AurumNativeBridge");webChromeClient=object:WebChromeClient(){override fun onJsPrompt(view:WebView?,url:String?,message:String?,defaultValue:String?,result:JsPromptResult?):Boolean{if(message?.startsWith("aurum://native?")==true){result?.confirm(handleNative(message,defaultValue.orEmpty()));return true};return super.onJsPrompt(view,url,message,defaultValue,result)}};webViewClient=object:WebViewClient(){override fun shouldInterceptRequest(view:WebView,request:WebResourceRequest)=loader.shouldInterceptRequest(request.url);override fun shouldOverrideUrlLoading(view:WebView,request:WebResourceRequest):Boolean{val u=request.url;if(u.scheme=="aurum"&&u.host=="complete"){finishActive(u.getQueryParameter("ok")!="0",u.getQueryParameter("detail").orEmpty());return true};return u.scheme!="https"||u.host!="appassets.androidplatform.net"}};loadUrl("https://appassets.androidplatform.net/assets/index.html?background=1&epoch="+work.epoch+"&pipeline="+work.kind)}}
 private fun finishActive(ok:Boolean,detail:String){val w=active?:return;watchdog?.let{handler.removeCallbacks(it)};watchdog=null;SchedulerLedger.complete(this,w.token,if(ok)"COMPLETED" else "FAILED",detail);destroyWebView();releaseWakeLock();active=null;handler.post{startNext()}}
 private fun handleNative(message:String,body:String):String{if(!message.startsWith("aurum://native?"))return "ERR:INVALID_NATIVE_URI";val u=runCatching{Uri.parse(message)}.getOrNull()?:return "ERR:INVALID_NATIVE_URI";return when(u.getQueryParameter("cmd").orEmpty()){"http_cancel"->{val id=u.getQueryParameter("requestId").orEmpty();if(id.isBlank())"ERR:MISSING_REQUEST_ID" else{NativeMarketHttp.cancel(id);"OK"}};"http_request"->{val id=u.getQueryParameter("requestId").orEmpty();val url=u.getQueryParameter("url").orEmpty();if(id.isBlank())"ERR:MISSING_REQUEST_ID" else if(url.isBlank())"ERR:MISSING_URL" else{NativeMarketHttp.request(this,id,u.getQueryParameter("method")?:"GET",url,body,(u.getQueryParameter("timeout")?.toIntOrNull()?:15000).coerceIn(1000,120000)){payload->resolveJs("window.AurumNativeHTTP&&window.AurumNativeHTTP.resolve",id,payload)};"ACCEPTED"}};"transfer_keepalive"->{if(u.getQueryParameter("enabled")!="0")acquireWakeLock() else releaseWakeLock();"OK"};else->"ERR:UNSUPPORTED_NATIVE_COMMAND"}}
 private fun resolveJs(fn:String,id:String,payload:String){handler.post{webView?.evaluateJavascript(fn+"("+JSONObject.quote(id)+","+JSONObject.quote(payload)+")",null)}}
 private fun acquireWakeLock(){if(wakeLock?.isHeld==true)return;wakeLock=(getSystemService(POWER_SERVICE) as PowerManager).newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"AurumB:BackgroundTransfer").apply{setReferenceCounted(false);acquire(2*60*60*1000L)}}
 private fun releaseWakeLock(){wakeLock?.let{if(it.isHeld)it.release()};wakeLock=null}
 private fun destroyWebView(){webView?.apply{stopLoading();loadUrl("about:blank");removeJavascriptInterface("AurumNativeBridge");removeAllViews();destroy()};webView=null}
 override fun onTimeout(startId:Int,fgsType:Int){finishActive(false,"ANDROID_FGS_TIMEOUT")}
 override fun onDestroy(){watchdog?.let{handler.removeCallbacks(it)};active?.let{SchedulerLedger.fail(this,it.token,"SERVICE_DESTROYED")};queue.forEach{SchedulerLedger.fail(this,it.token,"SERVICE_DESTROYED_BEFORE_START")};queue.clear();releaseWakeLock();destroyWebView();super.onDestroy()}
 override fun onBind(intent:Intent?):IBinder?=null
}