plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.aurum.bistterminal8'
    compileSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    defaultConfig {
        applicationId 'com.aurum.rev20.smartfastx.rebuild'
        minSdk 26
        targetSdk 35
        versionCode 10
        versionName '1.0.4-rev20.32'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.activity:activity-ktx:1.7.0'
    implementation 'androidx.webkit:webkit:1.12.1'
}
